### PR TITLE
Use gnome_basic rather then gnome-basic for consistency

### PR DESCRIPTION
**Pull request by simotek**

### CODE REVIEW

**Comment by jreidinger** [comment]
please fix package name as it is renamed now ( forgot to merge it ) and also please add ID (bsc or fate )

**Comment by jreidinger** [comment]
@simotek ping

**Comment by simotek** [comment]
Sorry i've been traveling the last week or so and missed this. i'll try and get it done soon

**Comment by teclator** [comment]
Already fixed by #10 so closing this one

**Pull request closed without merging**
